import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { EXPORTS_CONTENT_DIR, REPO_ROOT } from '../lib/config.mjs';

function encodeAvif(srcPng, destAvif, { size = 1280, crf = 34, lossless = false } = {}) {
  const args = ['-y', '-i', srcPng];
  if (size) args.push('-vf', `scale=${size}:${size}:flags=lanczos`);
  args.push('-c:v', 'libaom-av1', '-still-picture', '1');
  if (lossless) {
    args.push('-aom-params', 'lossless=1');
  } else {
    args.push('-crf', String(crf), '-cpu-used', '4');
  }
  args.push(destAvif);
  execFileSync('ffmpeg', args, { stdio: ['ignore', 'ignore', 'ignore'] });
}

const WORLDMAP_SRC = path.join(EXPORTS_CONTENT_DIR, 'UI', 'Game', 'WorldMap');
const WORLDMAP_DEST = path.join(REPO_ROOT, 'public', 'images', 'map');

const REGIONS = [
  { src: 'SetarTiles_ENG', dest: 'setar', overview: 'UndiscoveredArea/FXTest/TX_WorldMap.png' },
  { src: 'BalrogTiles', dest: 'balrog' },
  { src: 'CradleTiles', dest: 'cradle' },
];

function tileZoom(fileName) {
  const m = fileName.match(/^Tile([0-3]*)\.png$/);
  if (!m) return null;
  return m[1].length;
}

function tileXY(code, level) {
  let x = 0, y = 0;
  let size = 1 << level;
  for (const ch of code) {
    size >>= 1;
    const d = Number(ch);
    if (d === 1 || d === 3) x += size;
    if (d === 2 || d === 3) y += size;
  }
  return { x, y };
}

export function buildMapTiles() {
  let copiedCount = 0;
  const manifest = {};

  for (const region of REGIONS) {
    const srcDir = path.join(WORLDMAP_SRC, region.src);
    if (!fs.existsSync(srcDir)) continue;
    const destRoot = path.join(WORLDMAP_DEST, region.dest);
    fs.mkdirSync(destRoot, { recursive: true });

    const tiles = fs.readdirSync(srcDir).filter((f) => f.endsWith('.png'));
    const byZoom = {};
    for (const file of tiles) {
      const z = tileZoom(file);
      if (z == null) continue;
      const code = file.slice(4, -4);
      const { x, y } = code.length === 0 ? { x: 0, y: 0 } : tileXY(code, z);
      const zoomDir = path.join(destRoot, `z${z}`);
      fs.mkdirSync(zoomDir, { recursive: true });
      const destName = `${x}_${y}.png`;
      fs.copyFileSync(path.join(srcDir, file), path.join(zoomDir, destName));
      copiedCount++;
      (byZoom[z] ??= []).push({ x, y, file: destName });
    }

    const zoomSummary = {};
    for (const [z, arr] of Object.entries(byZoom)) {
      zoomSummary[z] = { tileCount: arr.length, gridSize: 1 << Number(z) };
    }

    let overviewUrl = null;
    if (region.overview) {
      const overviewSrc = path.join(WORLDMAP_SRC, region.overview);
      if (fs.existsSync(overviewSrc)) {
        const avifDest = path.join(destRoot, 'overview.avif');
        try {
          encodeAvif(overviewSrc, avifDest, { size: null, lossless: true });
          overviewUrl = `/images/map/${region.dest}/overview.avif`;
          const oldPng = path.join(destRoot, 'overview.png');
          if (fs.existsSync(oldPng)) fs.unlinkSync(oldPng);
          copiedCount++;
        } catch (err) {
          console.warn(`[datamine] AVIF encode failed for ${region.dest}, falling back to PNG:`, err.message);
          fs.copyFileSync(overviewSrc, path.join(destRoot, 'overview.png'));
          overviewUrl = `/images/map/${region.dest}/overview.png`;
          copiedCount++;
        }
      }
    }

    manifest[region.dest] = {
      publicPath: `/images/map/${region.dest}`,
      zoomLevels: Object.keys(byZoom).map(Number).sort((a, b) => a - b),
      tilePx: 512,
      zoomSummary,
      overviewUrl,
    };
  }

  const outTs = path.join(REPO_ROOT, 'src', 'data', 'map-tiles.ts');
  const contents =
    `// AUTO-GENERATED by scripts/datamine — do not edit\n` +
    `// Quadtree tile manifest per region. Tiles laid out as z{N}/{x}_{y}.png.\n\n` +
    `export interface MapTileRegion {\n` +
    `  publicPath: string;\n` +
    `  zoomLevels: number[];\n` +
    `  tilePx: number;\n` +
    `  zoomSummary: Record<string, { tileCount: number; gridSize: number }>;\n` +
    `  overviewUrl: string | null;\n` +
    `}\n\n` +
    `export const MAP_TILES: Record<string, MapTileRegion> = ${JSON.stringify(manifest, null, 2)};\n`;
  fs.writeFileSync(outTs, contents);

  return { count: copiedCount, outFile: outTs };
}
