// AUTO-GENERATED by scripts/datamine — do not edit
// Quadtree tile manifest per region. Tiles laid out as z{N}/{x}_{y}.png.

export interface MapTileRegion {
  publicPath: string;
  zoomLevels: number[];
  tilePx: number;
  zoomSummary: Record<string, { tileCount: number; gridSize: number }>;
  overviewUrl: string | null;
}

export const MAP_TILES: Record<string, MapTileRegion> = {
  "setar": {
    "publicPath": "/images/map/setar",
    "zoomLevels": [
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "tilePx": 512,
    "zoomSummary": {
      "0": {
        "tileCount": 1,
        "gridSize": 1
      },
      "1": {
        "tileCount": 4,
        "gridSize": 2
      },
      "2": {
        "tileCount": 16,
        "gridSize": 4
      },
      "3": {
        "tileCount": 64,
        "gridSize": 8
      },
      "4": {
        "tileCount": 256,
        "gridSize": 16
      },
      "5": {
        "tileCount": 1024,
        "gridSize": 32
      }
    },
    "overviewUrl": "/images/map/setar/overview.webp"
  },
  "balrog": {
    "publicPath": "/images/map/balrog",
    "zoomLevels": [
      0,
      1,
      2
    ],
    "tilePx": 512,
    "zoomSummary": {
      "0": {
        "tileCount": 1,
        "gridSize": 1
      },
      "1": {
        "tileCount": 4,
        "gridSize": 2
      },
      "2": {
        "tileCount": 16,
        "gridSize": 4
      }
    },
    "overviewUrl": null
  },
  "cradle": {
    "publicPath": "/images/map/cradle",
    "zoomLevels": [
      0,
      1,
      2
    ],
    "tilePx": 512,
    "zoomSummary": {
      "0": {
        "tileCount": 1,
        "gridSize": 1
      },
      "1": {
        "tileCount": 4,
        "gridSize": 2
      },
      "2": {
        "tileCount": 16,
        "gridSize": 4
      }
    },
    "overviewUrl": null
  }
};
